### ISSUE TITLE
Touch Gestures are not be Working

### ISSUE THREAD

**Issue by Deathraymind** [horriblename/hyprgrass#103]
​​   ​​ ​コンピューター 
                                              ┌──────────────────────────────────────────┐ 
                                               ​ ​​  OS : Arch Linux x86_64 
                                               ​​ ​  Kernel : 6.8.4-arch1-1 
                                               ​​ ​  Packages : 1349 (pacman), 48 (flatpak) 
                                               ​​ ​  Resolution : 1920x1080 
                                               ​​ ​  DE : Hyprland 
                                               ​​ ​  Terminal : kitty 
                                              └──────────────────────────────────────────┘ 
                                               
                                               ​​ ​​​  : goof@Trashcan 
                                              ┌──────────────────────────────────────────┐ 
                                               ​​ ​  CPU : Intel i7-8700 (12) @ 4.600GHz 
                                               ​​ ​  GPU : AMD ATI Radeon 540/540X/550/550X / RX 540X/550/550X 
                                               ​​ ​  GPU : AMD ATI Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT 
                                               ​​ ​  GPU Driver : amdgpu 
                                               ​​ ​ ﬙ Memory : 3734MiB / 31911MiB 
                                              └──────────────────────────────────────────┘ 
                                                 
Input device : Magic trackpad

I have made the following configs
hyprpm list
 → Repository hyprgrass:
  │ Plugin hyprgrass
  └─ enabled: true

**~/.config/hypr/hyprland.conf**

```
plugin:touch_gestures {
  # The default sensitivity is probably too low on tablet screens,
  # I recommend turning it up to 4.0
  sensitivity = 1.0

  # must be >= 3
  workspace_swipe_fingers = 3

  # switching workspaces by swiping from an edge, this is separate from workspace_swipe_fingers
  # and can be used at the same time
  # possible values: l, r, u, or d
  # to disable it set it to anything else
  workspace_swipe_edge = d

  # in milliseconds
  long_press_delay = 400


}
```

then 

```

# swipe left from right edge
bind = , edge:r:l, workspace, +1

# swipe up from bottom edge
bind = , edge:d:u, exec, firefox

# swipe down from left edge
bind = , edge:l:d, exec, pactl set-sink-volume @DEFAULT_SINK@ -4%

# swipe down with 4 fingers
# NOTE: swipe events only trigger for finger count of >= 3
bind = , swipe:4:d, killactive

# swipe diagonally left and down with 3 fingers
# l (or r) must come before d and u
bind = , swipe:3:ld, exec, foot

# tap with 3 fingers
# NOTE: tap events only trigger for finger count of >= 3
bind = , tap:3, exec, foot

# longpress can trigger mouse binds:
bindm = , longpress:2, movewindow
bindm = , longpress:3, resizewindow
```

any help would be great the docs are well made but I'm still haveing trouble.

**Comment by horriblename** [comment]
hyprgrass is a touch **screen** plugin

**Comment by Deathraymind** [comment]
Bruh... who.. nvm thanks idk how I missed that, ig it was late.
