### ISSUE TITLE
workspace_swipe_edge = d is completely broken

### ISSUE THREAD

**Issue by System64fumo** [horriblename/hyprgrass#105]
So i tried to enable workspace_swipe_edge=d in a previous version of hyprland (unsure what) and it caused hyprland to crash whenever i would finish (lift up the finger) swiping, So i decided to update both hyprland and hyprgrass (Big mistake)

Now when i swipe from left to right, It visually shows the right animation.
But the moment i lift up my finger it throws me back to the original workspace

But when swiping from right to left, It initially starts at workspace 2 then swipes to workspace 1 (but also doesn't) ((does not really switch workspaces))

Though i have very rarely after fiddling with it for a while managed to swipe to the other workspace successfully like 1 out of 10 tries

Excuse the lack of a video, Github/My browser seems to think the file is corrupt.

Edit:
Forgot to mention but this only happens with the edge swipe, Normal gestures work fine.

**Comment by horriblename** [comment]
hyprland now has builtin workspace swipe touch gestures, do use that for now


related: #100. seems like at this point a rewrite of workspace swipe needs to happen

**Comment by AmirDahan** [comment]
Ooo i didn't even notice that hyprland added touch gestures.
In that case i hope it won't take that long to rewrite using the new code.
