### ISSUE TITLE
Is this plugin only for the git version of Hyprland?

### ISSUE THREAD

**Issue by ibrahimbayyinah** [horriblename/hyprgrass#115]
I installed & enabled using `hyprpm`:
```shell
~ ➜  hyprpm list
 → Repository hyprgrass:
  │ Plugin hyprgrass
  └─ enabled: true
```
And I reloaded the plugins with `hyprpm reload -n`.

However, when I run `hyprctl systeminfo`, the `plugins` section is empty and `hyprctl plugin list` gives me: `no plugins loaded`. Needless to say, whatever configuration I try in my Hyprland config, it does nothing.

So does this plugin only work in the latest git version of Hyprland? I'm using the package from the official Arch repository (not AUR).

**Comment by horriblename** [comment]
you can try building hyprgrass 0.6 or even 0.5, but I'm not sure if that'll work (i didn't do a very good job tracking hyprland versions)

**Comment by Kruemmelspalter** [comment]
this plugin (v0.7; 5f01276371d0) works for me on Hyprland 0.41.2-1

**Comment by horriblename** [comment]
hyprpm pins should do a decently good job at finding older commits by now. usability on Hyprland < 0.40.0 is unknown and situation unlikely to change
