### ISSUE TITLE
hyprgrass failing to build (GestureManager.cpp)

### ISSUE THREAD

**Issue by leafina2895** [horriblename/hyprgrass#119]
When trying to install hyprgrass, it encounters an error when compiling `GestureManager.cpp` (see Sceenshot)
After using `hyprpm update -v`, you can enable hyprgrass, but the plugin fails as it cannot find `hyprgrass.so`.

![image](https://github.com/horriblename/hyprgrass/assets/126329893/11f462e9-b636-4451-be4c-642a55b881de)

OS: Arch Linux x86_64 (6.8.9-arch1-2)
Hyprland Version 0.40.0

I am new to linux and not used to submitting issues, so if you require any more logs or info please tell me! ^^

**Comment by horriblename** [comment]
currently hyprland-git branch breaks plugins, please use 0.40.0 instead (commit `cba1ade`, i wrote that from memory might be wrong)

if it still doesn't build/doesn't work on 0.40.0 let me know

**Comment by leafina2895** [comment]
I am not using the AUR package (`hyprland-git`), I am using the official package. (`hyprland-0.40.0-1`)
Is that still a wrong version?

**Comment by horriblename** [comment]
show `hyprctl version`?

**Comment by horriblename** [comment]
nevermind it's probably my fault, I'll push a fix later

**Comment by horriblename** [comment]
should be fixed now

**Comment by horriblename** [comment]
please open new issue if it persists
