### ISSUE TITLE
incorrect position mapping with multiple touch screens

### ISSUE THREAD

**Issue by Arbel-arad** [horriblename/hyprgrass#126]
when grabbing a window (with a 3-finger longpress) if the window is on a secondary display it will get teleported to the main display at the same x/y location.
i can still move it around in the mapped area and it follows the finger positions from screen 2 to screen 1.

grabbing windows on the primary screen works as intended.

**Comment by horriblename** [comment]
which commit?

**Comment by Arbel-arad** [comment]
hyprland 0.40.0-1
hyprgrass latest version from hyprpm

this issue has been going on since i first installed hyprgrass months ago but i assumed it was caused by an unrelated hyprland bug that was fixed a few days ago.

**Comment by horriblename** [comment]
I seem to have goofed up monitor detection, send me monitor + touch screen config

**Comment by Arbel-arad** [comment]
this is my hyprland monitor config

```bash
#-- Output -----------------------------------------------------
monitor = eDP-1,preferred,0x0,1.333333,bitdepth,10
monitor = DP-3,preferred,0x1622,1.333333,bitdepth,10
monitor = ,preferred,auto,1
#-- monitor=,preferred,auto,1,mirror,DP-1
```

**Comment by horriblename** [comment]
you have two touchscreen devices?

**Comment by Arbel-arad** [comment]
yes, i have a zenbook pro duo with two touch + pen inputs.

**Comment by horriblename** [comment]
I'm surprised it works at all, is anything else broken? aside from workspace swipes. Do edge swipes work?

**Comment by Arbel-arad** [comment]
workspace swipes only work on screen 1 (no response on screen 2)
edge swipes act the same as workspace swipes
tap actions work as expected
window dragging teleports the window to screen1 (as stated above)

**Comment by horriblename** [comment]
feel free to reopen if not fixed

**Comment by ForgotMyPasswd** [comment]
This doesn't work for me. While I don't have a device with two touchscreens, I use regularly two displays often which requires me to offset my touchscreen display if I want to place the other display above my touchscreen's display. The plugin seems to still be treating the display as if it has an offset of 0x0 even when it doesn't, with the only fix being to enter and exit sleep.

**Comment by Arbel-arad** [comment]
i tested it, looks like nothing changed.

**Comment by horriblename** [comment]
let me know if it works

I wanna make a release but I wanna first make sure this bug dies here

**Comment by Arbel-arad** [comment]
i updated everything, looks like it's all working now!
