### ISSUE TITLE
Increase touch margins

### ISSUE THREAD

**Issue by System64fumo** [horriblename/hyprgrass#142]
I don't think this is possible to do since it might be a wf-touch limitation but, would it be possible to increase touch margins?
Like for edge swipe gestures.
Add the ability to use custom sizes rather than 1px big which is rather hard to hit on some devices.

**Comment by horriblename** [comment]
#144 test pls

**Comment by System64fumo** [comment]
Doesn't seem to work?
Well it does do something but doesn't change margins?

I feel like it changes the margins by like 2-3 px or something
Setting it to/past 250 breaks it

**Comment by horriblename** [comment]
just tested this, works on my machine :tm:

the margins are measured in pixels, so for small devices you probably need a lot more than 10px.

Also the gestures might be interpreted as "corner" ones (e. g. `edge:ld:r`) if you swipe too close to a corner. The corner area grows as well if you increase the margin

corner area becoming too big might be a problem but I'm not sure how to solve that

you can use

```
tail -F $XDG_RUNTIME_DIR/hypr/HYPRLAND_INSTANCE_SIGNATURE/hyprland*.log
```
to see what gestures are triggered

**Comment by System64fumo** [comment]
Oddly enough this works now??
Weird.
Oh well, Good work @horriblename!
I wish to suggest something to compliment this feature but ig opening a seperate issue is more fitting.
See you there!
