### ISSUE TITLE
Hyprgrass stopped working after recent update

### ISSUE THREAD

**Issue by ForgotMyPasswd** [horriblename/hyprgrass#154]
(I'm not sure how to get logs for hyprgrass, if there's a way I'll provide them)
I recently updated hyprgrass and hyprland, and now hyprgrass has stopped working with none of my gestures being recognised.

System information:
Hyprland version: 0.42.0
Latest zen kernel
Latest hyprgrass commit (version 0.7 according to `hyprctl sysinfo`)

**Comment by horriblename** [comment]
hyprctl probably reported the wrong version because I forgot to update the version number (again)

rollback to 0.7 for now

**Comment by EvanSunde** [comment]
its not working for me too. I am using the latest hyprgrass, and hyprpm shows that its properly loaded. Is there any way to check the logs

**Comment by horriblename** [comment]
Currently works for me without issues on hyprland 0.44.0 `d679d200299ed4670f0d0f138c793d5f507b7cec` and hyprgrass latest.

please open a new issue if it still doesn't work
