### ISSUE TITLE
[Contribution] Build Container to compile

### ISSUE THREAD

**Issue by DevDorrejo** [horriblename/hyprgrass#155]
Hello,

I am creating a script to allow build hyprland plugins, allowing the users to have a clean host.

With hyprgrass, I successfully compile the plugins, but like a person that never use meson or ninja, don't know which folder/file need to be under $HOME/.config/hyprpm/hyprgrass folder, from the output of `ninja -C build`:

![image](https://github.com/user-attachments/assets/cad8aba1-ed86-4a7b-bce3-04e2e11b1721)

**Comment by horriblename** [comment]
not sure what you meant, build/src/hyprgrass.so is the plugin, without hyprpm you would put this in hyprland.conf:

```
plugin = /path/to/hyprgrass.so
```


I have no idea how hyprpm works so I can't help you with that

**Comment by DevDorrejo** [comment]
> not sure what you meant, build/src/hyprgrass.so is the plugin, without hyprpm you would put this in hyprland.conf:
> 
> ```
> plugin = /path/to/hyprgrass.so
> ```
> 
> I have no idea how hyprpm works so I can't help you with that

Thank you, I will look into that.

**Comment by horriblename** [comment]
closing since this is not directly related to hyprgrass issues (bug/feature request). If you have more questions please use https://github.com/horriblename/hyprgrass/discussions instead
