### ISSUE TITLE
where do I put the config?

### ISSUE THREAD

**Issue by prietus** [horriblename/hyprgrass#166]
I am havin triubles to understand where ti put the config for the plugin. I tried a single file sourced in hyrland.conf and in hyprland.conf itself but I cannot make it to work, thanks in advance
https://bepasty.priet.us/YoxYxcPs/+inline

**Comment by horriblename** [comment]
README was outdated I think, change

```
plugin:touch_gestures{
...
}
```

to

```
plugin {
  touch_gestures {
  ...
  }
}
```

**Comment by prietus** [comment]
tyvm!
