### ISSUE TITLE
Mismatching Hyprland version

### ISSUE THREAD

**Issue by Namnodorel** [horriblename/hyprgrass#172]
**Describe the bug**
Hyprgrass shows an error complaining about a mismatching Hyprland version. Both Hyprland and Hyprgrass are up to date and it's not clear to me how to bring them closer together.

No gestures I attempted to set up work.

**Log**

```
[LOG] Loading plugin /nix/store/...hyprgrass-v0.8.2-/lib/libhyprgrass.so which is now present in config
[ERR] [hyprgrass] version mismatch!
[ERR] [hyprgrass] | hyprgrass was built against: 3b66351eeb76e802bac37cc892529549efc49905
[ERR] [hyprgrass] | actual hyprland version: 4520b30d498daca8079365bdb909a8dea38e8d55
[LOG]  [PluginSystem] Plugin hyprgrass loaded. Handle: 1a61a7d0, path: "/nix/store/...-hyprgrass-v0.8.2-/lib/libhyprgrass.so", author: "horriblenam>
```

**Desktop:**
 - OS: NixOS
 - output of `hyprctl version`:
```
Hyprland, built from branch v0.44.1-b at commit 4520b30d498daca8079365bdb909a8dea38e8d55  (version: bump to 0.44.1).
Date: 2024-10-09
Tag: v0.44.1, commits: 4520b30d498daca8079365bdb909a8dea38e8d55
built against aquamarine 0.4.3
  ```

- output of `hyprctl plugin list`:
```
Plugin hyprgrass by horriblename:
        Handle: 1a61a7d0
        Version: v0.8.2
        Description: Touchscreen gestures
 ```

<details>
<summary> **Flake Config & Lock** </summary>

```
inputs = {
  nixpkgs.url = "github:NixOs/nixpkgs/nixos-unstable";
  hyprland = {
    url = "github:hyprwm/Hyprland";
  };

  hyprgrass = {
     url = "github:horriblename/hyprgrass";
     inputs.hyprland.follows = "hyprland";
  };
};
```
**flake.lock**
```
"hyprgrass": {
      "inputs": {
        "hyprland": [
          "hyprland"
        ]
      },
      "locked": {
        "lastModified": 1730322735,
        "narHash": "sha256-Jg5Q/v8tcNjopTMbra82y5n9QQdCnrbEFNgT1kA7pQE=",
        "owner": "horriblename",
        "repo": "hyprgrass",
        "rev": "f97b6ac2b7de3bae194b776c388467db2604929f",
        "type": "github"
      },
      "original": {
        "owner": "horriblename",
        "repo": "hyprgrass",
        "type": "github"
      }
    },
"hyprland": {
      "inputs": {
        "aquamarine": "aquamarine",
        "hyprcursor": "hyprcursor",
        "hyprland-protocols": "hyprland-protocols",
        "hyprlang": "hyprlang",
        "hyprutils": "hyprutils",
        "hyprwayland-scanner": "hyprwayland-scanner",
        "nixpkgs": "nixpkgs",
        "pre-commit-hooks": "pre-commit-hooks",
        "systems": "systems",
        "xdph": "xdph"
      },
      "locked": {
        "lastModified": 1731086737,
        "narHash": "sha256-J/SA5nriNVTzSfjaxBbjUnuRCKOzxnW71yK3fBU5iTs=",
        "owner": "hyprwm",
        "repo": "Hyprland",
        "rev": "3b66351eeb76e802bac37cc892529549efc49905",
        "type": "github"
      },
      "original": {
        "owner": "hyprwm",
        "repo": "Hyprland",
        "type": "github"
      }
    },
```

</details>

Note in particular how the revision reported by flake.lock (matching the most recent Hyprland Git commit and the one that hyprgrass was built against) is different from the revision reported by `hyprctl version` (the commit of that hyprland version).

**Comment by horriblename** [comment]
seems like a different version of hyprland is used. are you using hyprland from nixpkgs? how did you set up hyprland?

**Comment by Namnodorel** [comment]
I'm not sure what you're asking that isn't already answered by the flake config excerpt I posted above (note that it's collapsed by default to reduce visual spam). Do you want more details of the flake config, hyprland config, something else?

**Comment by horriblename** [comment]
you showed the input, but you could be using hyprland from nixpkgs and I wouldn't know. in any case, the hyprland you're running is definitely not the one locked in your input

**Comment by horriblename** [comment]
it could also be that you didn't restart hyprland after updating

**Comment by Namnodorel** [comment]
I now see what you meant. I was indeed still using nixpkgs hyprland somewhere else in my config without realizing. Removing/replacing it with the bleeding edge version finally updated the hyprctl output as well to match what I expected.

Unfortunately the bleeding edge build is broken for me (wayland fails to start) but that is no longer a problem concerning hyprgrass. Thank you for the quick reply and pointer!

**Comment by horriblename** [comment]
fyi you can build it off nixpkgs hyprland as well, with `hyprgrass.override {hyprland = pkgs.hyprland}` but you will need an older version of hyprgrass, probably v0.8.2 or v0.7.0
