### ISSUE TITLE
Building without NixOS or nix

### ISSUE THREAD

**Issue by matt1432** [horriblename/hyprgrass#26]
It would be nice to have instructions or clarifications on how to compile and use this plugin on a non NixOS system in the README.

**Comment by horriblename** [comment]
Completely forgot to do that, but [hyprload](https://github.com/Duckonaut/hyprload) should just work.

will add manual compilation instructions later

**Comment by matt1432** [comment]
This might not concern your project but explaining how to use hyprload to use this plugin might be nice, or please link me to any documentation because i'm not sure I understand how it works

**Comment by horriblename** [comment]
honestly, I've never used it myself, but from the README, it says to put this in `~/. config/hypr/hyprload.toml`:

```
plugins = [
    "horriblename/hyprland-touch-gestures" 
] 
```

do let me know if you need have any trouble, since hyprload is untested

**Comment by horriblename** [comment]
I've updated hyprload instructions on the README, let me know if it works

**Comment by matt1432** [comment]
> honestly, I've never used it myself, but from the README, it says to put this in `~/. config/hypr/hyprload.toml`:
> 
> ```
> plugins = [
>     "horriblename/hyprland-touch-gestures" 
> ] 
> ```
> 
> do let me know if you need have any trouble, since hyprload is untested

It doesn't work, I think there's an issue with the difference between the name of the repo and the name of the plugin in the toml.
I think I managed to make it work manually tho but my other [issue](https://github.com/horriblename/hyprland-touch-gestures/issues/27) is still there.
