### ISSUE TITLE
Crashing when loading plugin on launch

### ISSUE THREAD

**Issue by matt1432** [horriblename/hyprgrass#65]
When I open Hyprland with the plugin loaded from the start, it crashes. But if I don't and load the plugin after it works.
[hyprlandCrashReport3012.txt](https://github.com/horriblename/hyprgrass/files/13468678/hyprlandCrashReport3012.txt)

**Comment by matt1432** [comment]
I can fix it for now by adding this to my `exec-once`s in the home-manager module:
```nix
"sleep 3; hyprctl plugin load ${hyprgrass.packages.${pkgs.system}.default}/lib/libhyprgrass.so"
```

**Comment by horriblename** [comment]
seems resolved, can you test again?
