### ISSUE TITLE
resize / move window with touch

### ISSUE THREAD

**Issue by Arbel-arad** [horriblename/hyprgrass#67]
is there a way to resize window borders, or move floating windows using touch?
i couldn't find any way to bind "finger" like a mouse button.

i would like to have the option to switch windows to floating with a 4-finger tap on that window if possible.

**Comment by horriblename** [comment]
> is there a way to resize window borders, or move floating windows using touch?

nope, not at the moment. I might try hold gestures in the future tho

4 finger tap seems easy enough, I'll see if I can add it this weekend

**Comment by Arbel-arad** [comment]
i tested the tap function and it works perfectly.

my config:
4 fingers for float, 5 for fullscreen.

**Comment by Arbel-arad** [comment]
thank you,
3-finger long press and drag is working correctly.
