### ISSUE TITLE
hyprpm requires meson and ninja

### ISSUE THREAD

**Issue by YjzJim** [horriblename/hyprgrass#81]
hyprpm uses meson and ninja to build the package. Nevertheless, if meson is not present, it reports error like below. The problem can be easily diagnosed with --verbose in the add hyprpm command. I was wondering if i would be better to include this information in the install via hyprpm part.

![2024-01-18T11:13:11,313794068+08:00](https://github.com/horriblename/hyprgrass/assets/153434126/d265ab89-5cbd-4f64-bd2f-b0c0ccaae062)

**Comment by horriblename** [comment]
added to README, thanks!
