### ISSUE TITLE
broken on hyprland latest

### ISSUE THREAD

**Issue by horriblename** [horriblename/hyprgrass#90]
quick announcement: hyprgrass is broken on hyprland-git until further notice

**Comment by horriblename** [comment]
should be fixed in #91
I haven't tested (I can't)

pls tell me if I f'd up

**Comment by krlhBlupine** [comment]
I can build on hyprland-git, but the build fails on the main arch package version now.

**Comment by horriblename** [comment]
arch repo probably hasn't been updated yet, use the last hyprgrass release or commit 360bc1c2b590423d91ee7ee21049b55c5c7a1eaa
