### ISSUE TITLE
linux-surface compat (libwacom-surface)

### ISSUE THREAD

**Issue by krlhBlupine** [horriblename/hyprgrass#92]
I was just wondering if there are any plans to add compatibility with Surface touchscreens, or if I'm just missing the way to pass the libwacom output to hyprland.  Currently the only way to use the touchscreen on these with linux installed is with some kernel patches that haven't been upstreamed yet, and they still have some quirks when it comes to multitouch support.

(Checkout [here](https://github.com/linux-surface/linux-surface) if you're curious.)

**Comment by horriblename** [comment]
ok so it is my fault #93
