### ISSUE TITLE
hyprland carch with hyprgrass 

### ISSUE THREAD

**Issue by a-amr** [horriblename/hyprgrass#98]
Hyprland, built from branch  at commit 05c84304ccb1169b550504830139e07e28500a3b  ().
Date: 2024-03-19
Tag: 

flags: (if any)

System Information:
System name: Linux
Node name: xxx
Release: 6.8.1
Version: #1-NixOS SMP PREEMPT_DYNAMIC Fri Mar 15 18:19:29 UTC 2024

GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA106M [GeForce RTX 3060 Mobile / Max-Q] [10de:2520] (rev a1) (prog-if 00 [VGA controller])
06:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] [1002:1638] (rev c5) (prog-if 00 [VGA controller])

os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.20240316.c75037b"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"

plugins:
  hyprgrass by horriblename ver 0.5
  hyprbars by Vaxry ver 1.0
  borders-plus-plus by Vaxry ver 1.0

on standrd output after crash hyprland  give me this error  err:wayland.c:1942: failed to flush wayland socket:Brocken pipe

this is producible with any gesture

**Comment by horriblename** [comment]
bisect and/or logs would be helpful

**Comment by a-amr** [comment]
from where could i get those logs in nixos i gess from /tmp/hypr am i right

also i have a question because i didn’t try hyprgrass yet

# swipe up from bottom edge
bind = , edge:d:u, exec, firefox

# swipe down from left edge
bind = , edge:l:d, exec, …..

does these swipes same as edge scrolling which mean it does need only one finger 
i love edge scrolling but i just want to swap the right edge with the bottom because that’s alot more organomic and to be able to edit what the top and the left edge do is that even possible in hyprgrass or in any other tool i don’t think the libinput have this feature 
i have a fairly big touchpad so these gestures would be very useful for my use case

**Comment by horriblename** [comment]
sir, this is a touch __screen__ plugin

but still send me crash logs if they exist, in ~/.hyprland or ~/.cache/hyprland

**Comment by a-amr** [comment]
after updating hyprland to the last version i cant reproduce this problem again
