### ISSUE TITLE
[Question] 3 finger drag/select?

### ISSUE THREAD

**Issue by zahidkizmaz** [horriblename/hyprgrass#99]
Hello! Thank you so much for creating this amazing open-source plugin! 

I've been experimenting with it, and I wanted to add MacOS like three-finger select/drag functionality. 
Is that possible with this plugin? If so, Is there any documentation showing that how can it be done? 

Thank you!

**Comment by horriblename** [comment]
not sure what that is, send me a video or something?

**Comment by zahidkizmaz** [comment]
> not sure what that is, send me a video or something?

Sure thing, I found an example video: https://www.youtube.com/watch?v=40hGD-wU32A

I find this very useful for selecting text.

**Comment by horriblename** [comment]
hmm might be possible if I add custom mouse binds

lemme try something and I'll get back to you

**Comment by horriblename** [comment]
custom mouse binds were harder to implement than I thought, but even if we have that, my current API doesn't really allow for what you want.

If you want, it would probably be easier to just write a separate plugin at this point.

**Comment by zahidkizmaz** [comment]
> custom mouse binds were harder to implement than I thought, but even if we have that, my current API doesn't really allow for what you want.
> 
> If you want, it would probably be easier to just write a separate plugin at this point.

Thank you for trying and the effort.
